# Podfile
platform :ios, '13.0'
use_frameworks!

target 'Blooming' do
    pod 'Alamofire', '~> 5.2'
    pod 'RxSwift', '6.0.0'
    pod 'RxCocoa', '6.0.0'
    pod 'SwiftLint'
    pod 'Then'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'BloomingTests' do
    pod 'RxBlocking', '6.0.0'
    pod 'RxTest', '6.0.0'
end
