# Podfile
use_frameworks!

target 'EchoNote' do
    pod 'Alamofire', '~> 5.2'
    pod 'RxSwift', '6.0.0'
    pod 'RxCocoa', '6.0.0'
    pod 'SwiftLint'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'EchoNoteTests' do
    pod 'RxBlocking', '6.0.0'
    pod 'RxTest', '6.0.0'
end
